//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libs.Wpf.TestApplication.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(Translations.resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libs.Wpf.TestApplication.ViewModels.Translations", typeof(Translations).Assembly);
                    Translations.resourceMan = temp;
                }
                return Translations.resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return Translations.resourceCulture;
            }
            set {
                Translations.resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonLabel (de).
        /// </summary>
        internal static string ButtonLabel {
            get {
                return Translations.ResourceManager.GetString("ButtonLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonToolTip (de).
        /// </summary>
        internal static string ButtonToolTip {
            get {
                return Translations.ResourceManager.GetString("ButtonToolTip", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxErrorIsRequired (de).
        /// </summary>
        internal static string CheckBoxErrorIsRequired {
            get {
                return Translations.ResourceManager.GetString("CheckBoxErrorIsRequired", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxLabel (de).
        /// </summary>
        internal static string CheckBoxLabel {
            get {
                return Translations.ResourceManager.GetString("CheckBoxLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxToolTip (de).
        /// </summary>
        internal static string CheckBoxToolTip {
            get {
                return Translations.ResourceManager.GetString("CheckBoxToolTip", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxErrorIsRequired (de).
        /// </summary>
        internal static string ComboBoxErrorIsRequired {
            get {
                return Translations.ResourceManager.GetString("ComboBoxErrorIsRequired", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemLabel_0 (de).
        /// </summary>
        internal static string ComboBoxItemLabel_0 {
            get {
                return Translations.ResourceManager.GetString("ComboBoxItemLabel_0", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemLabel_1 (de).
        /// </summary>
        internal static string ComboBoxItemLabel_1 {
            get {
                return Translations.ResourceManager.GetString("ComboBoxItemLabel_1", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemLabel_2 (de).
        /// </summary>
        internal static string ComboBoxItemLabel_2 {
            get {
                return Translations.ResourceManager.GetString("ComboBoxItemLabel_2", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxLabel (de).
        /// </summary>
        internal static string ComboBoxLabel {
            get {
                return Translations.ResourceManager.GetString("ComboBoxLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxToolTip (de).
        /// </summary>
        internal static string ComboBoxToolTip {
            get {
                return Translations.ResourceManager.GetString("ComboBoxToolTip", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxWatermark (de).
        /// </summary>
        internal static string ComboBoxWatermark {
            get {
                return Translations.ResourceManager.GetString("ComboBoxWatermark", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpanderLabel (de).
        /// </summary>
        internal static string ExpanderLabel {
            get {
                return Translations.ResourceManager.GetString("ExpanderLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBoxLabel (de).
        /// </summary>
        internal static string GroupBoxLabel {
            get {
                return Translations.ResourceManager.GetString("GroupBoxLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label (de).
        /// </summary>
        internal static string Label {
            get {
                return Translations.ResourceManager.GetString("Label", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBoxIsRequired (de).
        /// </summary>
        internal static string PasswordBoxIsRequired {
            get {
                return Translations.ResourceManager.GetString("PasswordBoxIsRequired", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBoxLabel (de).
        /// </summary>
        internal static string PasswordBoxLabel {
            get {
                return Translations.ResourceManager.GetString("PasswordBoxLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBoxToolTip (de).
        /// </summary>
        internal static string PasswordBoxToolTip {
            get {
                return Translations.ResourceManager.GetString("PasswordBoxToolTip", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBoxWatermark (de).
        /// </summary>
        internal static string PasswordBoxWatermark {
            get {
                return Translations.ResourceManager.GetString("PasswordBoxWatermark", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit (de).
        /// </summary>
        internal static string SubmitButtonLabel {
            get {
                return Translations.ResourceManager.GetString("SubmitButtonLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitButtonToolTip (de).
        /// </summary>
        internal static string SubmitButtonToolTip {
            get {
                return Translations.ResourceManager.GetString("SubmitButtonToolTip", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockLabel (de).
        /// </summary>
        internal static string TextBlockLabel {
            get {
                return Translations.ResourceManager.GetString("TextBlockLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxLabel (de).
        /// </summary>
        internal static string TextBoxLabel {
            get {
                return Translations.ResourceManager.GetString("TextBoxLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxToolTip (de).
        /// </summary>
        internal static string TextBoxToolTip {
            get {
                return Translations.ResourceManager.GetString("TextBoxToolTip", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxValueIsRequired (de).
        /// </summary>
        internal static string TextBoxValueIsRequired {
            get {
                return Translations.ResourceManager.GetString("TextBoxValueIsRequired", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxWatermark (de).
        /// </summary>
        internal static string TextBoxWatermark {
            get {
                return Translations.ResourceManager.GetString("TextBoxWatermark", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Language (de).
        /// </summary>
        internal static string ToggleLanguageButtonLabel {
            get {
                return Translations.ResourceManager.GetString("ToggleLanguageButtonLabel", Translations.resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonToolTip (de).
        /// </summary>
        internal static string ToggleLanguageButtonToolTip {
            get {
                return Translations.ResourceManager.GetString("ToggleLanguageButtonToolTip", Translations.resourceCulture);
            }
        }
    }
}

}
