//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libs.Wpf.TestApplication.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libs.Wpf.TestApplication.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonLabel (de).
        /// </summary>
        internal static string ButtonLabel {
            get {
                return ResourceManager.GetString("ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonToolTip (de).
        /// </summary>
        internal static string ButtonToolTip {
            get {
                return ResourceManager.GetString("ButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxErrorIsRequired (de).
        /// </summary>
        internal static string CheckBoxErrorIsRequired {
            get {
                return ResourceManager.GetString("CheckBoxErrorIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxLabel (de).
        /// </summary>
        internal static string CheckBoxLabel {
            get {
                return ResourceManager.GetString("CheckBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBoxToolTip (de).
        /// </summary>
        internal static string CheckBoxToolTip {
            get {
                return ResourceManager.GetString("CheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxErrorIsRequired (de).
        /// </summary>
        internal static string ComboBoxErrorIsRequired {
            get {
                return ResourceManager.GetString("ComboBoxErrorIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxLabel (de).
        /// </summary>
        internal static string ComboBoxLabel {
            get {
                return ResourceManager.GetString("ComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxToolTip (de).
        /// </summary>
        internal static string ComboBoxToolTip {
            get {
                return ResourceManager.GetString("ComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxWatermark (de).
        /// </summary>
        internal static string ComboBoxWatermark {
            get {
                return ResourceManager.GetString("ComboBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpanderLabel (de).
        /// </summary>
        internal static string ExpanderLabel {
            get {
                return ResourceManager.GetString("ExpanderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupBoxLabel (de).
        /// </summary>
        internal static string GroupBoxLabel {
            get {
                return ResourceManager.GetString("GroupBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBoxIsRequired (de).
        /// </summary>
        internal static string PasswordBoxIsRequired {
            get {
                return ResourceManager.GetString("PasswordBoxIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBoxLabel (de).
        /// </summary>
        internal static string PasswordBoxLabel {
            get {
                return ResourceManager.GetString("PasswordBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBoxToolTip (de).
        /// </summary>
        internal static string PasswordBoxToolTip {
            get {
                return ResourceManager.GetString("PasswordBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordBoxWatermark (de).
        /// </summary>
        internal static string PasswordBoxWatermark {
            get {
                return ResourceManager.GetString("PasswordBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitButtonLabel (de).
        /// </summary>
        internal static string SubmitButtonLabel {
            get {
                return ResourceManager.GetString("SubmitButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitButtonToolTip (de).
        /// </summary>
        internal static string SubmitButtonToolTip {
            get {
                return ResourceManager.GetString("SubmitButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBlockLabel (de).
        /// </summary>
        internal static string TextBlockLabel {
            get {
                return ResourceManager.GetString("TextBlockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxLabel (de).
        /// </summary>
        internal static string TextBoxLabel {
            get {
                return ResourceManager.GetString("TextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxToolTip (de).
        /// </summary>
        internal static string TextBoxToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxValueIsRequired (de).
        /// </summary>
        internal static string TextBoxValueIsRequired {
            get {
                return ResourceManager.GetString("TextBoxValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxWatermark (de).
        /// </summary>
        internal static string TextBoxWatermark {
            get {
                return ResourceManager.GetString("TextBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleLanguageButtonLabel (de).
        /// </summary>
        internal static string ToggleLanguageButtonLabel {
            get {
                return ResourceManager.GetString("ToggleLanguageButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleLanguageButtonToolTip (de).
        /// </summary>
        internal static string ToggleLanguageButtonToolTip {
            get {
                return ResourceManager.GetString("ToggleLanguageButtonToolTip", resourceCulture);
            }
        }
    }
}
