name: Libs.Wpf
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
  packages: write
  id-token: write
  pages: write
jobs:
  build-and-test:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-build-and-test.yaml@main
    with:
      solution-directory: ./
      runs-on: windows-latest
  create-nuget:
    needs: build-and-test
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      project-name: Libs.Wpf
      solution-directory: .
      runs-on: windows-latest
  create-code-coverage-page:
    needs: create-nuget
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-code-coverage-page.yaml@main
    with:
      project-name: Libs.Wpf
      test-project-name: Libs.Wpf.Tests
      project-version: ${{needs.create-nuget.outputs.new-version}}
      solution-directory: .
      runs-on: windows-latest
      filefilters: -*.xaml;-*.xaml.cs;-*.g.cs;-*TextBox.cs;-*Adorner.cs;-*LocExtension.cs