name: Libs.Wpf
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  build-and-test:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-build-and-test.yaml@main
    with:
      solution-directory: ./
      runs-on: windows-latest
  create-nuget:
    needs: build-and-test
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-nuget.yaml@main
    with:
      project-name: Lib.Wpf
      solution-directory: .
      runs-on: windows-latest