name: Libs.Wpf
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-test:
    uses: MichaelDiers/github-workflows/.github/workflows/dotnet-build-and-test.yaml@main
    with:
      solution-directory: ./
      runs-on: windows-latest      